version: '2'
services:
  cassandra:
    build: ./cassandra-graphite
    container_name: cassandra
    ports:
     - "9042:9042"
    depends_on:
     - graphite
  graphite:
    image: sitespeedio/graphite:0.9.14
    container_name: graphite
    ports:
    - "2003:2003"
    - "8080:80"
  grafana:
    image: grafana/grafana:3.1.0
    container_name: grafana
    ports:
    - "3000:3000"
    depends_on:
    - graphite
